trying to fix sonarwube coverage

diff --git a/.github/workflows/sonar.yml b/.github/workflows/sonar.yml
--- a/.github/workflows/sonar.yml
+++ b/.github/workflows/sonar.yml
@@ -31,6 +31,13 @@ jobs:
           bundle exec rspec
 
 
+      - name: Verify coverage file
+        run: |
+          echo "Current working directory: $(pwd)"
+          ls -R munchora-server-relational-db | grep coverage || echo "No coverage dir found"
+          ls -lah munchora-server-relational-db/coverage || echo "coverage dir missing"
+
+
       - name: SonarQube Scan
         uses: SonarSource/sonarqube-scan-action@v6
         env:
